# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='predict.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\037com.microservice.k8sclient.grpcB\024PredictResourceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpredict.proto\"1\n\rhistoryStruct\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x01\"*\n\nhistoryReq\x12\x1c\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0e.historyStruct\"\x1d\n\x0bpredictResp\x12\x0e\n\x06result\x18\x01 \x03(\x01\x32\x37\n\x0fPredictResource\x12$\n\x07Predict\x12\x0b.historyReq\x1a\x0c.predictRespB9\n\x1f\x63om.microservice.k8sclient.grpcB\x14PredictResourceProtoP\x01\x62\x06proto3'
)




_HISTORYSTRUCT = _descriptor.Descriptor(
  name='historyStruct',
  full_name='historyStruct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='historyStruct.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='historyStruct.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=66,
)


_HISTORYREQ = _descriptor.Descriptor(
  name='historyReq',
  full_name='historyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='historyReq.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=110,
)


_PREDICTRESP = _descriptor.Descriptor(
  name='predictResp',
  full_name='predictResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='predictResp.result', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=141,
)

_HISTORYREQ.fields_by_name['data'].message_type = _HISTORYSTRUCT
DESCRIPTOR.message_types_by_name['historyStruct'] = _HISTORYSTRUCT
DESCRIPTOR.message_types_by_name['historyReq'] = _HISTORYREQ
DESCRIPTOR.message_types_by_name['predictResp'] = _PREDICTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

historyStruct = _reflection.GeneratedProtocolMessageType('historyStruct', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYSTRUCT,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:historyStruct)
  })
_sym_db.RegisterMessage(historyStruct)

historyReq = _reflection.GeneratedProtocolMessageType('historyReq', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYREQ,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:historyReq)
  })
_sym_db.RegisterMessage(historyReq)

predictResp = _reflection.GeneratedProtocolMessageType('predictResp', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESP,
  '__module__' : 'predict_pb2'
  # @@protoc_insertion_point(class_scope:predictResp)
  })
_sym_db.RegisterMessage(predictResp)


DESCRIPTOR._options = None

_PREDICTRESOURCE = _descriptor.ServiceDescriptor(
  name='PredictResource',
  full_name='PredictResource',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=143,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='PredictResource.Predict',
    index=0,
    containing_service=None,
    input_type=_HISTORYREQ,
    output_type=_PREDICTRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTRESOURCE)

DESCRIPTOR.services_by_name['PredictResource'] = _PREDICTRESOURCE

# @@protoc_insertion_point(module_scope)
